# Generated by Django 4.2 on 2023-05-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub_content1',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sub_content2',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sub_content3',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sub_content4',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sub_content5',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sub_content6',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sub_content7',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sub_content8',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sub_content9',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='sub_content',
            field=models.TextField(default='', null=True),
        ),
    ]
